#Requires -Version 5.1
[CmdletBinding()]
param([switch]$Check)
$ErrorActionPreference = 'Stop'
$version = (Get-Content -LiteralPath (Join-Path $PSScriptRoot 'version.json') -Raw | ConvertFrom-Json).version
if ($version -notmatch '^\d+\.\d+\.\d+$') { throw 'Invalid product version.' }
$manifest = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'packages\applications.json') -Raw
$manifest = $manifest.Replace("`r`n", "`n").Replace("`r", "`n")
$null = $manifest | ConvertFrom-Json
$parts = @(Get-ChildItem -LiteralPath (Join-Path $PSScriptRoot 'src\Provisioner') -Filter '*.ps1' | Sort-Object Name)
$content = ($parts | ForEach-Object { [IO.File]::ReadAllText($_.FullName).TrimEnd() }) -join "`r`n`r`n"
$content = $content.Replace("`r`n", "`n").Replace("`r", "`n").Replace("`n", "`r`n")
$content = $content.Replace('__PRODUCT_VERSION__', $version).Replace('__APPLICATION_MANIFEST_BASE64__', [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($manifest)))
$content = "# GENERATED by Build-Provisioner.ps1. Edit src/Provisioner, not this file.`r`n" + $content + "`r`n"
$tokens = $null; $errors = $null
$null = [Management.Automation.Language.Parser]::ParseInput($content, [ref]$tokens, [ref]$errors)
if ($errors.Count) { throw ($errors | Out-String) }
$target = Join-Path $PSScriptRoot 'Install-KiloLinkSuite.ps1'
if ($Check) {
    if (-not (Test-Path -LiteralPath $target) -or [IO.File]::ReadAllText($target) -cne $content) { throw 'Generated provisioner is stale. Run Build-Provisioner.ps1.' }
} else { [IO.File]::WriteAllText($target, $content, [Text.UTF8Encoding]::new($true)) }
Write-Output "Provisioner $version source verified."
